#!/bin/sh
# place in /usr/lib/systemd/system-sleep/
if [ "${1}" == "pre" ]; then
  # Do the thing you want before suspend here, e.g.:
  echo "suspending..."
elif [ "${1}" == "post" ]; then
  # Do the thing you want after resume here, e.g.:
 rmmod sky2
 modprobe sky2
fi
